name: Deploy
on:
    push:
        branches: [production]

jobs:
    deploy:
        uses: BijanProgrammerWebsites/hub/.github/workflows/deploy-docusaurus.yml@master
        with:
            host: docs.codestar.ir
            base-href: /
